name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ssh sam:ABC123drm1021@159.89.40.43 'cd /var/www/ovallogic.com/ & git clone https://github.com/samueleguino97/oval.git & cd oval & npm install & npm run build' 
      env:
        CI: true
